[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[features]
default = ["all"]
all = ["wgpu", "dx12", "image", "svg", "resources", "devtools"]
wgpu = ["lurq/wgpu"]
dx12 = ["lurq/dx12"]
image = ["lurq/image"]
svg = ["lurq/svg"]
resources = ["lurq/resources"]
devtools = ["lurq/devtools"]

[dependencies]
lurq = { path = "../lurq", default-features = false, features = ["winit"] }
